const products = {

  // BRACELETS
  'teal-tide': {
    name: '5 Stone Crystal Opal Bracelet | Sterling Silver | \'Teal Tide\'',
    price: 'AU$799',
    salePrice: 'AU$499',
    sale: true,
    metal: 'silver',
    image: 'bracelets/Teal Tide.jpg',
    category: 'bracelets',
  },
  'grand-shore': {
    name: '38.50ct Boulder Opal Bracelet | Sterling Silver | \'Grand Shore\'',
    price: 'AU$1,999',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'bracelets/Grand Shore.jpg',
    category: 'bracelets',
  },
  'sea-glass': {
    name: '4 Stone Light Opal Bracelet | Sterling Silver | \'Sea Glass\'',
    price: 'AU$799',
    salePrice: 'AU$499',
    sale: true,
    metal: 'silver',
    image: 'bracelets/Sea Glass.jpg',
    category: 'bracelets',
  },
  'reef-walk': {
    name: '5 Stone Light Opal Bracelet | Sterling Silver | \'Reef Walk\'',
    price: 'AU$799',
    salePrice: 'AU$499',
    sale: true,
    metal: 'silver',
    image: 'bracelets/Reef Walk.jpg',
    category: 'bracelets',
  },
  'ivory-oval': {
    name: '24.10ct Large Oval Opal Bracelet | Sterling Silver | \'Ivory Oval\'',
    price: 'AU$1,499',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'bracelets/Ivory Oval.jpg',
    category: 'bracelets',
  },
  'teardrop-shore': {
    name: '19.35ct Crystal Opal Bracelet | Sterling Silver | \'Teardrop Shore\'',
    price: 'AU$2,499',
    salePrice: 'AU$1,499',
    sale: true,
    metal: 'silver',
    image: 'bracelets/Teardrop Shore.jpg',
    category: 'bracelets',
  },
  'soft-light': {
    name: '21.80ct Large Stone Opal Bracelet | Sterling Silver | \'Soft Light\'',
    price: 'AU$1,499',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'bracelets/Soft Light.jpg',
    category: 'bracelets',
  },
  'white-shore': {
    name: '17.60ct Large Stone Opal Bracelet | Sterling Silver | \'White Shore\'',
    price: 'AU$1,199',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'bracelets/White Shore.jpg',
    category: 'bracelets',
  },
  'crystal-flex': {
    name: '8.90ct Crystal Opal Bracelet | Sterling Silver | \'Crystal Flex\'',
    price: 'AU$799',
    salePrice: 'AU$499',
    sale: true,
    metal: 'silver',
    image: 'bracelets/Crystal Flex.jpg',
    category: 'bracelets',
  },
  'pearl-tide': {
    name: '6.80ct Opal Bracelet | Sterling Silver | \'Pearl Tide\'',
    price: 'AU$799',
    salePrice: 'AU$499',
    sale: true,
    metal: 'silver',
    image: 'bracelets/Pearl Tide.jpg',
    category: 'bracelets',
  },
  'double-stack': {
    name: '12.40ct Crystal Opal Double Stack | Sterling Silver | \'Double Stack\'',
    price: 'AU$599',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'bracelets/Double Stacks.jpg',
    category: 'bracelets',
  },
  'white-cuff': {
    name: '15.20ct Crystal Opal Cuff | Sterling Silver | \'White Cuff\'',
    price: 'AU$699',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'bracelets/White Cuff.jpg',
    category: 'bracelets',
  },
  'coastal-wave': {
    name: '20.80ct Solid Semi-Black Opal Bracelet | Sterling Silver | \'Coastal Wave\'',
    price: 'AU$1,499',
    salePrice: 'AU$999',
    sale: true,
    metal: 'silver',
    image: 'bracelets/Coastal Wave.jpg',
    category: 'bracelets',
  },
  'outback-cuff': {
    name: '32.15ct Boulder Opal Bracelet | Sterling Silver | \'Outback Cuff\'',
    price: 'AU$1,499',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'bracelets/Outback Cuff.jpg',
    category: 'bracelets',
  },
  'green-garden': {
    name: '10 Stone Crystal Opal Bracelet | Sterling Silver | \'Green Garden\'',
    price: 'AU$599',
    salePrice: 'AU$349',
    sale: true,
    metal: 'silver',
    image: 'bracelets/Green Garden.jpg',
    category: 'bracelets',
  },

// EARRINGS
  'crystal-whisper': {
    name: '9.65ct Natural Crystal Opal Studs | Sterling Silver | \'Crystal Whisper\'',
    price: 'AU$799',
    salePrice: 'AU$499',
    sale: true,
    metal: 'silver',
    image: 'earrings/Crystal Whisper.jpg',
    category: 'earrings',
  },
  'white-mist': {
    name: '9.65ct Solid White Opal Studs | Sterling Silver | \'White Mist\'',
    price: 'AU$599',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'earrings/White Mist.jpg',
    category: 'earrings',
  },
  'polar-light': {
    name: '23.40ct Crystal Opal Studs | Sterling Silver | \'Polar Light\'',
    price: 'AU$799',
    salePrice: 'AU$499',
    sale: true,
    metal: 'silver',
    image: 'earrings/Polar Light.jpg',
    category: 'earrings',
  },
  'lagoon-light': {
    name: '43.25ct Boulder Opal Drop Earrings | 10K Yellow Gold | \'Lagoon Light\'',
    price: 'AU$2,999',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'earrings/Lagoon Light.jpg',
    category: 'earrings',
  },
  'colour-bars': {
    name: '25ct Crystal Opal Drop Earrings | 10K Yellow Gold | \'Colour Bars\'',
    price: 'AU$1,299',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'earrings/Colour Bars.jpg',
    category: 'earrings',
  },
  'violet-dream': {
    name: '24.10ct Crystal Teardrop Opal Earrings | Sterling Silver | \'Violet Dream\'',
    price: 'AU$999',
    salePrice: 'AU$699',
    sale: true,
    metal: 'silver',
    image: 'earrings/Violet Dream.jpg',
    category: 'earrings',
  },
  'ivory-drop': {
    name: '4.75ct White Opal Drop Earrings | Sterling Silver | \'Ivory Drop\'',
    price: 'AU$799',
    salePrice: 'AU$499',
    sale: true,
    metal: 'silver',
    image: 'earrings/Ivory Drop.jpg',
    category: 'earrings',
  },
  'coastal-eclipse': {
    name: '45.20ct Boulder Opal Studs | 10K Yellow Gold | \'Coastal Eclipse\'',
    price: 'AU$1,699',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'earrings/Coastal Eclipse.jpg',
    category: 'earrings',
  },
  'twin-moons': {
    name: '23.40ct Boulder Opal Drop Earrings | Sterling Silver | \'Twin Moons\'',
    price: 'AU$2,999',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'earrings/Twin Moons.jpg',
    category: 'earrings',
  },
  'emerald-star': {
    name: '45.20ct Crystal Opal Earrings | 10K Yellow Gold | \'Emerald Star\'',
    price: 'AU$3,199',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'earrings/Emerald Star.jpg',
    category: 'earrings',
  },
  'golden-tide': {
    name: '32.15ct Boulder Opal Drop Earrings | 10K Yellow Gold | \'Golden Tide\'',
    price: 'AU$2,999',
    salePrice: 'AU$2,499',
    sale: true,
    metal: 'gold',
    image: 'earrings/Golden Tide.jpg',
    category: 'earrings',
  },
  'snow-drop': {
    name: '6.15ct White Opal Drop Earrings | Sterling Silver | \'Snow Drop\'',
    price: 'AU$399',
    salePrice: 'AU$249',
    sale: true,
    metal: 'silver',
    image: 'earrings/Snow Drop.jpg',
    category: 'earrings',
  },
  'crystal-falls': {
    name: '2.35ct Crystal Opal Drop Earrings | Sterling Silver | \'Crystal Falls\'',
    price: 'AU$399',
    salePrice: 'AU$249',
    sale: true,
    metal: 'silver',
    image: 'earrings/Crystal Falls.jpg',
    category: 'earrings',
  },
  'peacock-pair': {
    name: '5.85ct Crystal Opal Drop Earrings | Sterling Silver | \'Peacock Pair\'',
    price: 'AU$799',
    salePrice: 'AU$499',
    sale: true,
    metal: 'silver',
    image: 'earrings/Peacock Pair.jpg',
    category: 'earrings',
  },
  'silver-love': {
    name: '2.15ct White Opal Earrings | Sterling Silver | \'Silver Love\'',
    price: 'AU$299',
    salePrice: 'AU$199',
    sale: true,
    metal: 'silver',
    image: 'earrings/Silver Love.jpg',
    category: 'earrings',
  },
  'light-pools': {
    name: '43.20ct Boulder Opal Drop Earrings | 10K Yellow Gold | \'Light Pools\'',
    price: 'AU$6,499',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'earrings/Light Pools.jpg',
    category: 'earrings',
  },
  'golden-shores': {
    name: '15.23ct Boulder Opal Drop Earrings | 10K Yellow Gold | \'Golden Shores\'',
    price: 'AU$1,999',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'earrings/Golden Shores.jpg',
    category: 'earrings',
  },
  'stormy-skies': {
    name: '35ct Boulder Opal Drop Earrings | Sterling Silver | \'Stormy Skies\'',
    price: 'AU$1,499',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'earrings/Stormy Skies.jpg',
    category: 'earrings',
  },
  'crystal-pools': {
    name: '20.25ct Crystal Opal Drop Earrings | Sterling Silver | \'Crystal Pools\'',
    price: 'AU$999',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'earrings/Crystal Pools.jpg',
    category: 'earrings',
  },
  'flash-and-awe': {
    name: '12.45ct Crystal Opal Drop Earrings | Sterling Silver | \'Flash and Awe\'',
    price: 'AU$1,499',
    salePrice: 'AU$999',
    sale: true,
    metal: 'silver',
    image: 'earrings/Flash and Awe.jpg',
    category: 'earrings',
  },
  'manta-ray': {
    name: '1.25ct Crystal Opal Drop Earrings | Sterling Silver | \'Manta Ray\'',
    price: 'AU$499',
    salePrice: 'AU$299',
    sale: true,
    metal: 'silver',
    image: 'earrings/Manta Rays.jpg',
    category: 'earrings',
  },
// NECKLACES
  'golden-classic': {
    name: '3.40ct Crystal Opal Necklace | 10K Yellow Gold | \'Golden Classic\'',
    price: 'AU$599',
    salePrice: 'AU$349',
    sale: true,
    metal: 'gold',
    image: 'necklaces/Golden Classic.jpg',
    category: 'necklaces',
  },
  'brilliant-drop': {
    name: '10.55ct Boulder Opal Necklace | 10K Yellow Gold | \'Brilliant Drop\'',
    price: 'AU$1,199',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'necklaces/Brilliant Drop.jpg',
    category: 'necklaces',
  },
  'shadow-fall': {
    name: '42.95ct Boulder Opal Necklace | 10K Yellow Gold | \'Shadow Fall\'',
    price: 'AU$2,999',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'necklaces/Shadow Fall.jpg',
    category: 'necklaces',
  },
  'silver-statement': {
    name: '4.75ct Natural Crystal Opal Necklace | Sterling Silver | \'Silver Statement\'',
    price: 'AU$599',
    salePrice: 'AU$349',
    sale: true,
    metal: 'silver',
    image: 'necklaces/Statement Opal Necklace.jpg',
    category: 'necklaces',
  },
  'twin-hearts': {
    name: '2.15ct Crystal Opal Necklace | 10K Yellow Gold | \'Twin Hearts\'',
    price: 'AU$599',
    salePrice: 'AU$349',
    sale: true,
    metal: 'gold',
    image: 'necklaces/Twin Hearts.jpg',
    category: 'necklaces',
  },
  'petal-bloom': {
    name: '1.20ct Crystal Opal Necklace | Sterling Silver | \'Petal Bloom\'',
    price: 'AU$599',
    salePrice: 'AU$349',
    sale: true,
    metal: 'silver',
    image: 'necklaces/Petal Bloom.jpg',
    category: 'necklaces',
  },
  'heart-glow': {
    name: '1.80ct Crystal Opal Necklace | 10K Yellow Gold | \'Heart Glow\'',
    price: 'AU$599',
    salePrice: 'AU$349',
    sale: true,
    metal: 'gold',
    image: 'necklaces/Heart Glow.jpg',
    category: 'necklaces',
  },
  'wave-rider': {
    name: '2.80ct Crystal Opal Necklace | 10K Yellow Gold | \'Wave Rider\'',
    price: 'AU$599',
    salePrice: 'AU$349',
    sale: true,
    metal: 'gold',
    image: 'necklaces/Wave Rider.jpg',
    category: 'necklaces',
  },
  'moonbeam-drop': {
    name: '10.15ct Queensland Boulder Necklace | Sterling Silver | \'Moonbeam Drop\'',
    price: 'AU$599',
    salePrice: 'AU$349',
    sale: true,
    metal: 'silver',
    image: 'necklaces/Moonbeam Drop.jpg',
    category: 'necklaces',
  },
  'winged-light': {
    name: '3.10ct Crystal Opal Necklace | 10K Yellow Gold | \'Winged Light\'',
    price: 'AU$599',
    salePrice: 'AU$349',
    sale: true,
    metal: 'gold',
    image: 'necklaces/Winged Light.jpg',
    category: 'necklaces',
  },
  'hook-line': {
    name: '5.30ct Crystal Opal Necklace | 10K Yellow Gold | \'Hook Line\'',
    price: 'AU$599',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'necklaces/Hook Line.jpg',
    category: 'necklaces',
  },
  'wish-upon-a-star': {
    name: '36ct Crystal Opal Necklace | Sterling Silver | \'Wish Upon A Star\'',
    price: 'AU$2,299',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'necklaces/Wish Upon A Star.jpg',
    category: 'necklaces',
  },
  'lightning-strike': {
    name: '26.45ct Boulder Opal Necklace | 10K Yellow Gold | \'Lightning Strike\'',
    price: 'AU$1,999',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'necklaces/Lightning Strike.jpg',
    category: 'necklaces',
  },
  'spectral-fire': {
    name: '30ct Queensland Boulder Necklace | 10K Yellow Gold | \'Spectral Fire\'',
    price: 'AU$8,999',
    salePrice: 'AU$5,999',
    sale: true,
    metal: 'gold',
    image: 'necklaces/Spectral Fire.jpg',
    category: 'necklaces',
  },
  'poseidon': {
    name: '6.60ct Solid Black Opal Necklace | Sterling Silver | \'Poseidon\'',
    price: 'AU$2,699',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'necklaces/Poseidon.jpg',
    category: 'necklaces',
  },
  'river-fire': {
    name: '28.90ct Boulder Opal Necklace | 10K Yellow Gold | \'River Fire\'',
    price: 'AU$2,999',
    salePrice: 'AU$1,999',
    sale: true,
    metal: 'gold',
    image: 'necklaces/River Fire.jpg',
    category: 'necklaces',
  },
  'dark-tide': {
    name: '29.90ct Boulder Opal Necklace | 10K Yellow Gold | \'Dark Tide\'',
    price: 'AU$3,199',
    salePrice: 'AU$2,199',
    sale: true,
    metal: 'gold',
    image: 'necklaces/Dark Tide.jpg',
    category: 'necklaces',
  },
  'soul-of-the-sea': {
    name: '74.90ct Solid Black Opal Necklace | Sterling Silver | \'Soul of the Sea\'',
    price: 'AU$16,999',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'necklaces/Soul of the Sea.jpg',
    category: 'necklaces',
  },
// RINGS
  'aurora-mist': {
    name: '25ct Queensland Boulder Ring | Sterling Silver | \'Aurora Mist\'',
    price: 'AU$799',
    salePrice: 'AU$499',
    sale: true,
    metal: 'silver',
    image: 'rings/Aurora Mist.jpg',
    category: 'rings',
  },
  'silver-whisper': {
    name: '17.45ct Queensland Boulder Ring | Sterling Silver | \'Silver Whisper\'',
    price: 'AU$799',
    salePrice: 'AU$499',
    sale: true,
    metal: 'silver',
    image: 'rings/Silver Whisper.jpg',
    category: 'rings',
  },
  'earthen-blaze': {
    name: '16ct Queensland Boulder Ring | 10K Yellow Gold | \'Earthen Blaze\'',
    price: 'AU$1,999',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'rings/Earthen Blaze.jpg',
    category: 'rings',
  },
  'iron-ridge': {
    name: '48.10ct Natural Crystal Opal Ring | Sterling Silver | \'Iron Ridge\'',
    price: 'AU$699',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'rings/Iron Ridge.jpg',
    category: 'rings',
  },
  'ocean-soul': {
    name: '14.60ct Natural Boulder Ring | 10K Yellow Gold | \'Ocean Soul\'',
    price: 'AU$3,999',
    salePrice: 'AU$2,499',
    sale: true,
    metal: 'gold',
    image: 'rings/Ocean Soul.jpg',
    category: 'rings',
  },
  'tezcatlipoca': {
    name: '27.55ct Queensland Boulder Ring | 10K Yellow Gold | \'Tezcatlipoca\'',
    price: 'AU$4,499',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'rings/Tezcatlipoca.jpg',
    category: 'rings',
  },
  'forest-flame': {
    name: '14.65ct Natural Crystal Opal Ring | 10K Yellow Gold | \'Forest Flame\'',
    price: 'AU$1,999',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'rings/Forest Flame.jpg',
    category: 'rings',
  },
  'tidal-dream': {
    name: '12.20ct Queensland Boulder Ring | 9K Yellow Gold | \'Tidal Dream\'',
    price: 'AU$2,599',
    salePrice: 'AU$1,599',
    sale: true,
    metal: 'gold',
    image: 'rings/Tidal Dream.jpg',
    category: 'rings',
  },
  'ocean-trilogy': {
    name: '17.85ct Lightning Ridge Black Opal Ring | Sterling Silver | \'Ocean Trilogy\'',
    price: 'AU$999',
    salePrice: 'AU$649',
    sale: true,
    metal: 'silver',
    image: 'rings/Ocean Trilogy.jpg',
    category: 'rings',
  },
  'ocean-drift': {
    name: '24.20ct Queensland Boulder Ring | Sterling Silver | \'Ocean Drift\'',
    price: 'AU$699',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'rings/Ocean Drift.jpg',
    category: 'rings',
  },
  'ocean-breeze': {
    name: '22.45ct Queensland Boulder Ring | Sterling Silver | \'Ocean Breeze\'',
    price: 'AU$799',
    salePrice: 'AU$499',
    sale: true,
    metal: 'silver',
    image: 'rings/Ocean Breeze.jpg',
    category: 'rings',
  },
  'endless-blue': {
    name: '13.75ct Queensland Boulder Ring | 10K Yellow Gold | \'Endless Blue\'',
    price: 'AU$2,199',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'rings/Endless Blue.jpg',
    category: 'rings',
  },
  'pearl-of-fire': {
    name: '29.40ct Queensland Boulder Ring | 10K Yellow Gold | \'Pearl of Fire\'',
    price: 'AU$3,499',
    salePrice: 'AU$2,499',
    sale: true,
    metal: 'gold',
    image: 'rings/Pearl of Fire.jpg',
    category: 'rings',
  },
  'storm-breaker': {
    name: '60.25ct Natural Crystal Opal Ring | Sterling Silver | \'Storm Breaker\'',
    price: 'AU$799',
    salePrice: 'AU$499',
    sale: true,
    metal: 'silver',
    image: 'rings/Storm Breaker.jpg',
    category: 'rings',
  },
  'midnight-tide': {
    name: '17.20ct Queensland Boulder Ring | Sterling Silver | \'Midnight Tide\'',
    price: 'AU$699',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'rings/Midnight Tide.jpg',
    category: 'rings',
  },
  'aurora-earth': {
    name: '2.21ct Queensland Boulder Ring | Sterling Silver | \'Aurora Earth\'',
    price: 'AU$799',
    salePrice: 'AU$499',
    sale: true,
    metal: 'silver',
    image: 'rings/Aurora Earth.jpeg',
    category: 'rings',
  },
  'stone-sea': {
    name: '20.90ct Queensland Boulder Ring | Sterling Silver | \'Stone and Sea\'',
    price: 'AU$799',
    salePrice: 'AU$499',
    sale: true,
    metal: 'silver',
    image: 'rings/Stone & Sea.jpg',
    category: 'rings',
  },
  'window-to-the-outback': {
    name: '11.70ct Queensland Boulder Ring | 9K Yellow Gold | \'Window to the Outback\'',
    price: 'AU$1,499',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'rings/Window to the Outback.jpg',
    category: 'rings',
  },
  'flame-of-passion': {
    name: '64.55ct Queensland Boulder Ring | 9K Yellow Gold | \'Flame of Passion\'',
    price: 'AU$4,999',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'rings/Flame of Passion.jpg',
    category: 'rings',
  },
  'blue-brilliance': {
    name: '25.40ct Lightning Ridge Black Opal Ring | 9K Yellow Gold | \'Blue Brilliance\'',
    price: 'AU$1,999',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'rings/Blue Brilliance.jpg',
    category: 'rings',
  },
  'prismatic-flash': {
    name: '11.65ct Queensland Boulder Ring | 10K Yellow Gold | \'Prismatic Flash\'',
    price: 'AU$3,499',
    salePrice: 'AU$2,499',
    sale: true,
    metal: 'gold',
    image: 'rings/Prismatic Flash.jpg',
    category: 'rings',
  },
  'clover-circle': {
    name: '12.05ct Lightning Ridge Black Opal Ring | 9K Yellow Gold | \'Clover Circle\'',
    price: 'AU$1,999',
    salePrice: 'AU$1,499',
    sale: true,
    metal: 'gold',
    image: 'rings/Clover Circle.jpg',
    category: 'rings',
  },
  'misty-crystal': {
    name: '12.35ct Natural Crystal Opal Ring | 9K Yellow Gold | \'Misty Crystal\'',
    price: 'AU$1,499',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'rings/Misty Crystal.jpg',
    category: 'rings',
  },
  'fire-on-the-plains': {
    name: '13.20ct Natural Crystal Opal Ring | Sterling Silver | \'Fire on the Plains\'',
    price: 'AU$1,999',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'rings/Fire on the Plains.jpg',
    category: 'rings',
  },
  'artic-bloom': {
    name: '2.12ct Natural Crystal Opal Ring | Sterling Silver | \'Artic Bloom\'',
    price: 'AU$699',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'rings/Artic Bloom.jpg',
    category: 'rings',
  },
  'midnight-blaze': {
    name: '53.55ct Lightning Ridge Black Opal Ring | Sterling Silver | \'Midnight Blaze\'',
    price: 'AU$999',
    salePrice: 'AU$649',
    sale: true,
    metal: 'silver',
    image: 'rings/Midnight Blaze.jpg',
    category: 'rings',
  },
  'desert-colour': {
    name: '14.20ct Natural Crystal Opal Ring | 9K Yellow Gold | \'Desert Colour\'',
    price: 'AU$1,499',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'rings/Desert Colour.jpg',
    category: 'rings',
  },
  'constellation': {
    name: 'Multi Stone Crystal Opal Ring | 9K Yellow Gold | \'Constellation\'',
    price: 'AU$1,499',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'rings/Constellation.jpg',
    category: 'rings',
  },
  'serpent-fire': {
    name: '4.73ct Queensland Boulder Ring | 10K Yellow Gold | \'Serpent Fire\'',
    price: 'AU$799',
    salePrice: 'AU$499',
    sale: true,
    metal: 'gold',
    image: 'rings/Serpent Fire.jpg',
    category: 'rings',
  },
  'coloured-depth': {
    name: '13.85ct Lightning Ridge Black Opal Ring | 9K Yellow Gold | \'Coloured Depth\'',
    price: 'AU$1,699',
    salePrice: null,
    sale: false,
    metal: 'gold',
    image: 'rings/Coloured Depths.jpg',
    category: 'rings',
  },
// MENS
  'earth-cord': {
    name: '66.90ct Matrix Boulder Opal on Cord | \'Earth Cord\'',
    price: 'AU$399',
    salePrice: null,
    sale: false,
    metal: null,
    image: 'mens/Earth Cord.jpg',
    category: 'mens',
  },
  'terra': {
    name: '25.65ct Matrix Boulder Opal on Cord | \'Terra\'',
    price: 'AU$399',
    salePrice: null,
    sale: false,
    metal: null,
    image: 'mens/Terra.jpg',
    category: 'mens',
  },
  'midnight-deal': {
    name: '82.50ct Matrix Boulder Cufflinks | Sterling Silver | \'Midnight Deal\'',
    price: 'AU$599',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'mens/Midnight Deal.jpg',
    category: 'mens',
  },
  'the-power': {
    name: '55ct Solid Crystal Opal Cufflinks | Sterling Silver | \'The Power\'',
    price: 'AU$999',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'mens/The Power.jpg',
    category: 'mens',
  },
  'electric-bolt': {
    name: '101.50ct Matrix Boulder Opal Cufflinks | Sterling Silver | \'Electric Bolt\'',
    price: 'AU$999',
    salePrice: null,
    sale: false,
    metal: 'silver',
    image: 'mens/Electric Bolt.jpg',
    category: 'mens',
  },
};

const params = new URLSearchParams(window.location.search);
const id = params.get('id');
const product = products[id];

if (product) {
  document.getElementById('product-img').src = product.image;
  document.getElementById('product-name').textContent = product.name;
  document.getElementById('product-price').textContent = product.price;
  document.getElementById('product-description').textContent = product.description;
  document.getElementById('breadcrumb-name').textContent = product.name.toUpperCase();
  document.getElementById('breadcrumb-category').href = product.category + '.html';
  document.getElementById('breadcrumb-category').textContent = product.categoryName;
  document.title = product.name + ' — Majulix';
  document.getElementById('product-video').src = `https://www.youtube.com/embed/${product.videoId}`;

  const detailsDiv = document.getElementById('product-details');
  let detailsHTML = '<h3>PRODUCT DETAILS</h3>';
  for (const [key, value] of Object.entries(product.details)) {
    detailsHTML += `<p><strong>${key}:</strong> ${value}</p>`;
  }
  detailsDiv.innerHTML = detailsHTML;

const thumbnails = document.querySelectorAll('.thumbnail');
  if (product.images) {
    product.images.forEach((img, index) => {
      if (thumbnails[index]) {
        thumbnails[index].src = img;
        thumbnails[index].addEventListener('click', () => {
          document.getElementById('product-img').src = img;
          thumbnails.forEach(t => t.classList.remove('active'));
          thumbnails[index].classList.add('active');
        });
      }
    });
  }
}

const otherProducts = Object.entries(products).filter(([key]) => key !== id);
const shuffled = otherProducts.sort(() => Math.random() - 0.5);
const exploring = shuffled.slice(0, 4);

const cards = document.querySelectorAll('.explore-card');
const images = document.querySelectorAll('.explore-img');

exploring.forEach(([key, p], index) => {
  const num = index + 1;

  if (cards[index]) cards[index].href = `products.html?id=${key}`;

  if (images[index]) {
    images[index].src = p.image;
    images[index].alt = p.name;
  }

  const nameEl = document.getElementById(`explore-name-${num}`);
  const priceEl = document.getElementById(`explore-price-${num}`);

  if (nameEl) nameEl.textContent = p.name;
  if (priceEl) priceEl.textContent = p.price;
});